// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6STy1Ls7YR2ND2RTK__ejgWYHTmSRJgM',
    appId: '1:7955765353:web:4dff35f5665383f0762af8',
    messagingSenderId: '7955765353',
    projectId: 'write-it-down-e07e5',
    authDomain: 'write-it-down-e07e5.firebaseapp.com',
    storageBucket: 'write-it-down-e07e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm3FC6Thu8JXuKqDBDmyHBawKQxp590J0',
    appId: '1:7955765353:android:58cba3ad329bdd66762af8',
    messagingSenderId: '7955765353',
    projectId: 'write-it-down-e07e5',
    storageBucket: 'write-it-down-e07e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQOIVk4MkUSKn2Eanm4N5oGxj9XGi0p7w',
    appId: '1:7955765353:ios:4221171d02304aca762af8',
    messagingSenderId: '7955765353',
    projectId: 'write-it-down-e07e5',
    storageBucket: 'write-it-down-e07e5.firebasestorage.app',
    iosBundleId: 'com.example.writeItDown',
  );

}